### ISSUE TITLE
when I run  "briefcase run android"， “Obtaining device skin... Unable to download pixel_3a device skin; is your computer offline?”

### ISSUE THREAD

**Issue by zengduo** [beeware/beeware.github.io#475] opened 2022-04-28 02:19 UTC
**Describe the bug**
when I run: "briefcase run android", 

Obtaining device skin...
Unable to download pixel_3a device skin; is your computer offline?

but my computer is online

**Screenshots**
![image](https://user-images.githubusercontent.com/9933502/165663182-9b68f1e1-f70a-4c0d-8efa-9d2d1610bfe6.png)

**Environment:**
 - Operating System:win10
 - Python version:3.9

**Comment by freakboy3742** [comment] 2022-04-28 02:24
"Is your computer offline" is a general suggestion; what is being reported here is that Briefcase is unable to download a specific file. The most common cause is being offline, but any other connectivity issue could be the cause (e.g., a firewall, a temporary network glitch, etc). 

The first thing to do is retry the run; if it was a temporary network glitch, it's possible that the issue will self-resolve.

If that doesn't work, the link that is Briefcase is attempting to download is `https://android.googlesource.com/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-master-dev/artwork/resources/device-art-resources/pixel_3a.tar.gz`. Are you able to download that URL?

**Comment by wd444847661** [comment] 2022-07-23 06:25
> "Is your computer offline" is a general suggestion; what is being reported here is that Briefcase is unable to download a specific file. The most common cause is being offline, but any other connectivity issue could be the cause (e.g., a firewall, a temporary network glitch, etc).
> 
> The first thing to do is retry the run; if it was a temporary network glitch, it's possible that the issue will self-resolve.
> 
> If that doesn't work, the link that is Briefcase is attempting to download is `https://android.googlesource.com/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-master-dev/artwork/resources/device-art-resources/pixel_3a.tar.gz`. Are you able to download that URL?

Hi:
    I met the same issue. I can download the item from the url you provided. So can I download the skin and put it somewhere mannuly in my computer to solove this issue?

**Comment by freakboy3742** [comment] 2022-07-24 23:36
@wd444847661 If you unpack that tarball as `~/.briefcase/tools/android_sdk/skins/pixel_3a` (there should be a file named `~/.briefcase/tools/android_sdk/skins/pixel_3a/layout` after unpacking), you should be able to continue to the next step. However, the next step is to download a collection of android system tools, and there's no (easy) way to work around this download - it's managed by the Android SDK. If you've got a firewall or something else blocking network access, it would be worth resolving that problem, because otherwise you're going to continue to have problems. The Android tooling assumes that it has network access.

Closing this ticket on the basis that the question has been answered (plus, it's been reported against the wrong repository)

**Closed by freakboy3742** 2022-07-24 23:36 UTC
Labels: question

**Comment by xihuaxixuegui** [comment] 2024-02-22 08:14
Hello, I also encountered the problem of the upstream, how can I finally solve it?

**Comment by freakboy3742** [comment] 2024-02-22 21:42
@xihuaxixuegui Have you tried any of the debugging steps mentioned in this thread?

**Comment by xihuaxixuegui** [comment] 2024-02-23 08:40
Thank you for your answer, I have solved the previous problem, and now there is a new problem, it says that I don't have hardware acceleration, but I have enabled acceleration in the bios, and I have downloaded HAXM
![Uploading OV3(KO0C%MC5WG_805I`]OT.png…]()

**Comment by xihuaxixuegui** [comment] 2024-02-23 08:40
Android emulator was unable to start!

Try starting the emulator manually by running:

    $ C:\Users\weicaigan\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\emulator\emulator.exe @beePhone -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm

**Comment by freakboy3742** [comment] 2024-02-23 23:59
@xihuaxixuegui Again - have you tried the step that the error message is telling you to try?

**Comment by xihuaxixuegui** [comment] 2024-02-24 16:14
I failed to launch the Android emulator in the briefcase run android step, it says I don't have a hardware acceleration driver, and I still can't start the Android emulator after installing the HAXM acceleration driver.

**Comment by rmartin16** [comment] 2024-02-24 16:29
@xihuaxixuegui 

What is the emulator printing on the screen? It usually says why it cannot start. Hardware acceleration is the likely problem but is not always the root issue.

Google provides general troubleshooting steps here: https://developer.android.com/studio/run/emulator-troubleshooting

**Comment by xihuaxixuegui** [comment] 2024-02-24 16:46
The emulator did not start successfully, showing this
![_~SMNLM~G0AJXZN 7XTVDA4](https://github.com/beeware/beeware.github.io/assets/145464916/38d59423-26f8-4b1d-bb9f-282cb0d080a4)

**Comment by rmartin16** [comment] 2024-02-24 16:56
That's just what Briefcase prints when the emulator fails to start.

Can you upload the log file mentioned in yellow in your screenshot?

**Comment by xihuaxixuegui** [comment] 2024-02-24 16:58
Uh-huh, down here
![@5 F5G(YN47APG7VUZU5_Q](https://github.com/beeware/beeware.github.io/assets/145464916/61006194-ed12-4c90-8cf6-85a1adcd9d32)

**Comment by xihuaxixuegui** [comment] 2024-02-24 16:59
thank you！

**Comment by rmartin16** [comment] 2024-02-24 17:01
That's still just what Briefcase is printing when the emulator fails to start.

Please stop uploading screenshots and upload the log file that Briefcase created instead.

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:10
Hello, I didn't find the log file you said, I thought it was what you were talking about.

**Comment by rmartin16** [comment] 2024-02-24 17:11
This one:
![image](https://github.com/beeware/beeware.github.io/assets/387848/acc5145a-48fa-4e99-a4d9-3918abdb133d)

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:13
That's what I just took a screenshot of.

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:16
Okay, please wait

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:16
[Uploading briefcase.2024_02_25-00_44_43.run.log…]()

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:52
[Uploading briefcase.2024_02_25-00_44_43.run.log…]()

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:54
Hello, I have a problem uploading a file, let me take a screenshot to show you.
![7QTOG}1{3D` WFB`{9E1_B1](https://github.com/beeware/beeware.github.io/assets/145464916/3bdff53e-fd8b-443a-b1f0-8fb1fb8166f7)

**Comment by xihuaxixuegui** [comment] 2024-02-24 17:56
When I execute this line of code $C:UsersweicaiganAppDataLocalBeeWarebriefcaseCachetoolsandroid_sdkemulatoremulator.exe @beePhone -dns-server 8.8.8.8 in cmd, it prompts me that I don't have a hardware driver

**Comment by xihuaxixuegui** [comment] 2024-02-24 18:25
Here is the link to the file, please help me take a look.https://drive.google.com/file/d/1MHEFeeBRYgrrpFbRzdStvJGeBX5lzz-_/view?usp=drive_link

**Comment by rmartin16** [comment] 2024-02-24 18:47
The links below from the output of the emulator are your best sources to get the emulator working on your machine. Once the emulator can run, Briefcase can use it.
```
ERROR   | x86_64 emulation currently requires hardware acceleration!                                                                                  android_sdk.py:1086
CPU acceleration status: Android Emulator hypervisor driver is not installed on this machine                                                          android_sdk.py:1086
More info on configuring VM acceleration on Windows:                                                                                                  android_sdk.py:1086
https://developer.android.com/studio/run/emulator-acceleration#vm-windows                                                                             android_sdk.py:1086
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.                                                  android_sdk.py:1086
```

**Comment by xihuaxixuegui** [comment] 2024-02-25 13:03
Thank you very much, the previous issue was resolved. But I encountered a new problem, after the Android emulator opened, the application was a blank interface without the tutorial said say hello.
![05$_8$~`LC7$~ TETE_9YBQ](https://github.com/beeware/beeware.github.io/assets/145464916/3def85ec-f15e-46e3-8936-395092f527e6)

**Comment by rmartin16** [comment] 2024-02-25 16:43
You should run `briefcase run android -u` to ensure the app that runs in the Android Emulator includes the latest version of the source code.

Also, you're using Python 3.7 which is too old to use with recent Briefcase releases; therefore, you're using quite an old version of Briefcase. You should use a newer version of Python and use it to recreate the environment with it to run Briefcase.

Finally, please create new [Discussions](https://github.com/beeware/briefcase/discussions) in the Briefcase repository for these questions.

**Comment by xihuaxixuegui** [comment] 2024-02-26 13:59
Thank you, yes, it's true that because my version is too low, this issue has been solved
