### ISSUE TITLE
Documentation overview/pointers for complete new-bees

### ISSUE THREAD

**Issue by BruceEckel** [beeware/beeware.github.io#134] opened 2017-05-22 18:02 UTC
Going to the home page, I don't know where to start. Russ explained there is no single point of entry, but the newbie needs to know that and how to make the initial decision about where to start.

Once I get further along and have an understanding of this I might be able to come back and make a pull request.

**Comment by jgirardet** [comment] 2019-02-08 21:54
Hi,
I'm a today newbee. I was a bit lost going to tuto then briefcase, ...
Then I looked at the Pycon video, it's very clear :
```
create your venv and activate it
pip install beeware
beeware new  # answer the questions
beeware build linux  # or ios macos ....
```
it's as simple as it but the doc is not aware of it :thinking:

**Comment by freakboy3742** [comment] 2020-05-10 04:31
Closing this as an effective duplicate of #121.

**Closed by freakboy3742** 2020-05-10 04:31 UTC
