### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by dzc0d3r** [beeware/beeware.github.io#388] opened 2020-04-06 22:32 UTC
I'm following the instructions as described in the README.rst file
i created a virtual environment venv, activated the virtual environment and install lektor via `pip install lektor` , but when i run `lektor server` i'm getting this error **ModuleNotFoundError: No module named 'werkzeug.contrib'**

**i'm on xubuntu 18.04 machine
using python 3.6.9 and virtualenv**

and this is the full traceback :
```

Traceback (most recent call last):
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/lektor/cli.py", line 627, in main
    cli.main(args=args, prog_name=name)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/lektor/cli.py", line 380, in server_cmd
    ctx.load_plugins()
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/lektor/cli.py", line 131, in load_plugins
    initialize_plugins(self.get_env())
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/lektor/pluginsystem.py", line 122, in initialize_plugins
    plugins = load_plugins()
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/lektor/pluginsystem.py", line 116, in load_plugins
    rv[ep.name] = ep.load()
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/m4dc0d3r/.cache/lektor/packages/8516064711b3f942b474124a547c8a58/lektor_atom.py", line 17, in <module>
    from werkzeug.contrib.atom import AtomFeed
ModuleNotFoundError: No module named 'werkzeug.contrib'


```

**Comment by freakboy3742** [comment] 2020-04-07 06:34
Ah - this is an annoying bug; but I haven't found a way to fix it as part of the install process.

The issue is that Werkzeug 1.0 removed it's contrib module, and lektor-atom hasn't been updated to reflect this. 

You can fix this locally by running:

    pip install -U "Werkzeug<1.0"

This will ensure that you have a compatible version of Werkzeug installed. The longer term fix is to update lektor-atom, or find an alternative.

**Comment by dzc0d3r** [comment] 2020-04-07 21:32
Using :`pip install -U "Werkzeug<1.0"` did the trick, i'm now able to start lektor server, and yes this is an annoying bug and the fix is to update lektor-atom or use something else as you mentioned already 👍

**Comment by freakboy3742** [comment] 2020-04-07 23:01
Unfortunately, lektor-atom hasn't been updated since 2018. There *is* [a PR to fix the problem](https://github.com/nixjdm/lektor-atom/pull/25), but it hasn't been merged. 

The [ticket connected to that PR](https://github.com/nixjdm/lektor-atom/issues/23) suggests that the Pallets website uses [a custom plugin](pallets/website@4021a91) and suggests it may be "near drop in compatible". While I'd rather use an standalone package, given that lektor-atom appears to be abandoned, we may need to move to our own in-repository copy of the Pallets solution. 

@dzc0d3r Would you care to make an attempt at a port?

**Comment by dzc0d3r** [comment] 2020-04-08 02:53
i will try and work on own in-repository copy of lektor-atom based on this [PR to fix the problem](https://github.com/nixjdm/lektor-atom/pull/25)

**Closed** 2020-04-10 23:56 UTC
